In [20]:
import pandas as pd
import numpy as np

In [21]:
data=pd.read_csv("../covid.csv")
data.head()

no   pc     wbc      mc   ast      bc     ldh  diagnosis
0   1  Low     Low     Low  High  Normal  Normal       True
1   2  Low     Low  Normal  High  Normal    High       True
2   3  Low    High  Normal  High  Normal  Normal      False
3   4  Low    High  Normal  High    High  Normal       True
4   5  Low  Normal    High  High  Normal  Normal      False

In [22]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
pc=le.fit_transform(data["pc"].values)
wbc=le.fit_transform(data["wbc"].values)
mc=le.fit_transform(data["mc"].values)
ast=le.fit_transform(data["ast"].values)
bc=le.fit_transform(data["bc"].values)
ldh=le.fit_transform(data["ldh"].values)

Y=le.fit_transform(data["diagnosis"].values)

In [23]:
X=np.array(list(zip(pc,wbc,mc,ast,bc,ldh)))
X

array([[1, 1, 1, 0, 1, 1],
       [1, 1, 2, 0, 1, 0],
       [1, 0, 2, 0, 1, 1],
       [1, 0, 2, 0, 0, 1],
       [1, 2, 0, 0, 1, 1],
       [1, 2, 2, 0, 1, 0],
       [2, 1, 1, 0, 1, 1],
       [2, 0, 2, 0, 1, 1],
       [2, 0, 2, 0, 0, 0],
       [2, 2, 0, 0, 1, 1],
       [2, 2, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1],
       [0, 2, 0, 1, 1, 1],
       [0, 2, 0, 1, 0, 0],
       [0, 0, 2, 1, 1, 0],
       [1, 2, 0, 0, 0, 1],
       [2, 2, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 0],
       [2, 2, 2, 0, 1, 1],
       [2, 0, 2, 0, 1, 0],
       [2, 1, 2, 0, 1, 0],
       [1, 0, 2, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [0, 0, 2, 1, 1, 1],
       [0, 2, 2, 1, 1, 1]])

In [24]:
Y

array([1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0], dtype=int64)

In [39]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,classification_report,precision_recall_fscore_support,roc_curve
from sklearn.model_selection import train_test_split
NB=MultinomialNB()

In [40]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [41]:
NB.fit(X_train,Y_train)
Y_pred=NB.predict(X_test)

In [42]:
accuracy_score(Y_test,Y_pred)

0.8

In [32]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      0.75      0.75         4

    accuracy                           0.60         5
   macro avg       0.38      0.38      0.38         5
weighted avg       0.60      0.60      0.60         5



In [43]:
roc_curve(Y_test,Y_pred)

(array([0.        , 0.33333333, 1.        ]),
 array([0., 1., 1.]),
 array([2, 1, 0], dtype=int64))