In [40]:
import pandas as pd
import numpy as np

In [41]:
data=pd.read_csv("../glass.csv")
data.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [42]:
from sklearn.svm import SVC
from sklearn import svm

In [53]:
X=data.drop("Type",axis=1)
Y=data["Type"]

In [44]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y)

In [45]:
linear=SVC(kernel="linear")
linear.fit(X_train,Y_train)

SVC(kernel='linear')

In [46]:
Y_prec=linear.predict(X_test)

In [47]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print("accuracy-linear : ",accuracy_score(Y_test,Y_prec))
print(classification_report(Y_test,Y_prec))
print("Confustion matrix: ")
print(confusion_matrix(Y_test,Y_prec))

accuracy-linear :  1.0
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        24
           3       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         3
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         6

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54

Confustion matrix: 
[[19  0  0  0  0  0]
 [ 0 24  0  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  0  3  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  6]]


In [48]:
model1=SVC(kernel='poly')
model2=SVC(kernel='sigmoid')
model3=SVC(kernel='rbf')

In [49]:
model1.fit(X_train,Y_train)
y_prec_m1=model1.predict(X_test)
accuracy_score(Y_test,y_prec_m1)

0.9444444444444444

In [50]:
model2.fit(X_train,Y_train)
y_prec_m2=model2.predict(X_test)
accuracy_score(Y_test,y_prec_m2)

0.7777777777777778

In [51]:
model3.fit(X_train,Y_train)
y_prec_m3=model3.predict(X_test)
accuracy_score(Y_test,y_prec_m3)

0.9074074074074074