In [58]:
from sklearn import svm
from sklearn.svm import SVC
import numpy as np
import pandas as pd

In [59]:
data=pd.read_csv("../glass.csv")
data.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [61]:
x=data.drop('Type',axis=1)
y=data.Type

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [63]:
linear=svm.SVC(kernel='linear')
linear.fit(x_train,y_train)

SVC(kernel='linear')

In [64]:
print(linear.n_support_)

[1 2 2 3 4 3]


In [65]:
y_pre=linear.predict(x_test)

In [66]:
from sklearn.metrics import accuracy_score


print("accuracy : ",accuracy_score(y_test,y_pre))

accuracy :  1.0


In [67]:
from sklearn.metrics import classification_report
print("/report")
print(classification_report(y_test,y_pre))

/report
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        29
           3       1.00      1.00      1.00         2
           5       1.00      1.00      1.00         4
           6       1.00      1.00      1.00         3
           7       1.00      1.00      1.00         8

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65



In [68]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pre))

[[19  0  0  0  0  0]
 [ 0 29  0  0  0  0]
 [ 0  0  2  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  0  8]]


In [69]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

In [70]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [71]:
y_pred1=model1.predict(x_test)
y_pred2=model2.predict(x_test)
y_pred3=model3.predict(x_test)

In [72]:
print("predicted by model1",accuracy_score(y_test,y_pred1))
print("predicted by model2",accuracy_score(y_test,y_pred2))
print("predicted by model3",accuracy_score(y_test,y_pred3))

predicted by model1 0.7384615384615385
predicted by model2 0.9384615384615385
predicted by model3 0.8923076923076924
